import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { NotificationProvider } from '@/providers/NotificationProvider';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Meme Chat',
    description: 'Generated by Nguyễn Phúc Hậu',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                style={{
                    backgroundColor: 'var(--color-background)',
                    color: 'var(--color-text)',
                }}
            >
                <NotificationProvider>{children}</NotificationProvider>
            </body>
        </html>
    );
}
